### ISSUE TITLE
你好、我用了这个插件了，发现字体变大以后行间距确不变、字体都被剃头了

### ISSUE THREAD

**Issue by hongdong** [adad184/MMNavigatorFont#1]
字体变大以后行间距确不变、字体都被剃头了

**Comment by adad184** [comment]
这个确实是这样的  不建议把字体调的太大 

不过可以下个版本考虑根据字体大小来调整行距    :)

**Comment by leeyyl** [comment]
Xcode 7.2显示不出来菜单

**Comment by adad184** [comment]
@WallaceYYLi Xcode 7.2的问题 刷新一下控件应该就好了  具体可以看这里 http://www.jianshu.com/p/db3d34a54031
