### ISSUE TITLE
Does not run on  xcode 7.2.1

### ISSUE THREAD

**Issue by edoardoc** [adad184/MMNavigatorFont#2]
Does not run on  xcode 7.2.1 running on 10.10.5 if compiled for 10.11, after compiling for 10.10.5 it works fine

**Comment by adad184** [comment]
``` shell
#!/bin/bash

UUID=$(defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID)
echo Xcode DVTPlugInCompatibilityUUID is $UUID

for MyPlugin in ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/*
do
    defaults write "$MyPlugin"/Contents/Info DVTPlugInCompatibilityUUIDs -array-add $UUID
    echo write DVTPlugInCompatibilityUUID to $MyPlugin succeed!
done
```

is this shell script helped?

**Comment by edoardoc** [comment]
no, it didn't it still goes:

`
2016-03-24 12:36:50.479 Xcode[3173:401954] WARNING: Failed to load plugin at path: "/Users/eddy/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MMNavigatorFont.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3588 "The bundle “MMNavigatorFont” couldn’t be loaded." (dlopen(/Users/eddy/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MMNavigatorFont.xcplugin/Contents/MacOS/MMNavigatorFont, 265): Symbol not found: ___NSArray0__
  Referenced from: /Users/eddy/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MMNavigatorFont.xcplugin/Contents/MacOS/MMNavigatorFont (which was built for Mac OS X 10.11)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Users/eddy/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MMNavigatorFont.xcplugin/Contents/MacOS/MMNavigatorFont) UserInfo=0x7fb1e5eaa720 {NSLocalizedFailureReason=The bundle couldn’t be loaded., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/eddy/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MMNavigatorFont.xcplugin/Contents/MacOS/MMNavigatorFont, NSDebugDescription=dlopen(/Users/eddy/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MMNavigatorFont.xcplugin/Contents/MacOS/MMNavigatorFont, 265): Symbol not found: ___NSArray0__
  Referenced from: /Users/eddy/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MMNavigatorFont.xcplugin/Contents/MacOS/MMNavigatorFont (which was built for Mac OS X 10.11)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Users/eddy/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MMNavigatorFont.xcplugin/Contents/MacOS/MMNavigatorFont, NSBundlePath=/Users/eddy/Library/Application Support/Developer/Shared/Xcode/Plug-ins/MMNavigatorFont.xcplugin, NSLocalizedDescription=The bundle “MMNavigatorFont” couldn’t be loaded.}
`

**Comment by adad184** [comment]
so, you build it on your Mac, but not installed from Alcatraz?

**Comment by edoardoc** [comment]
the log I posted was from alcatraz.
I got it working recompiling it setting target 10.10.5 (I found it by accident, while trying to enable debug symbols..)

**Comment by adad184** [comment]
sorry i can't debug it right now because i upgrade my Xcode to 7.3.   but the code definitely works because i build & run it successful on 10.11.4 with Xcode 7.3  :)

**Comment by adad184** [comment]
sorry  i understand the problem now,  so it's the project settings problem, i'll fix it.

**Comment by adad184** [comment]
I always upgrade to the latest version of OS X , so i forget to check the compatibility, my bad

**Comment by edoardoc** [comment]
thanks!
